FROM python:3.8-slim

RUN apt-get update && apt-get install -y \
    libgomp1

RUN pip install mlflow

EXPOSE 5000

ENV MLFLOW_TRACKING_URI=http://0.0.0.0:5000

CMD ["mlflow", "server", "--host", "0.0.0.0"]
